version: "3.9"

services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: client-container
    ports:
      - "5173:5173"
    env_file:
      - ./client/.env

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: server-container
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env