version: "3.9"

services:
  client:
    build: client
    ports:
      - "5173:5173"
    networks:
      - timetable

  server:
    build: server
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=timetable_cse
    networks:
      - timetable

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: timetable_cse
      MYSQL_ROOT_PASSWORD: ""
    networks:
      - timetable

networks: 
  timetable:
    driver: bridge
